In [2]:
import sys

print(sys.executable)
print(sys.version)

/Users/lipikam/Desktop/MinorProject/ANSC4040MiniProject/.venv/bin/python
3.12.14 (main, Aug 25 2026, 13:50:33) [Clang 22.1.3 ]

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [2]:
import pandas as pd

file_path = "/Users/lipikam/Desktop/MinorProject/ANSC4040MiniProject/project_1_ANSC_4040_dataset.csv"

df = pd.read_csv(file_path)

print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

display(df.head())

Rows: 8,495,421
Columns: 10

/var/folders/wm/1jg9q6hn6qb190_w715mhp100000gn/T/ipykernel_8046/1732501586.py:5: DtypeWarning: Columns (0: ReproductionStatus) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,AnimalNumber,LactationNumber,DaysInMilk,ReproductionStatus,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
0,31317.0,2.0,255.0,Pregnant,2.812273,2.898455,5.874021,8.028585,168,2
1,60614.0,1.0,251.0,Pregnant,2.902991,3.801104,6.372973,7.030682,143,1
2,36947.0,1.0,183.0,Pregnant,3.401943,3.701314,7.048825,16.374685,285,3
3,31720.0,2.0,82.0,Bred,4.309128,4.799007,8.876803,18.461209,256,1
4,23630.0,6.0,182.0,Pregnant,3.719457,3.701314,7.874364,13.199538,210,3

In [3]:
df_summary = pd.DataFrame({
    "DataType": df.dtypes,
    "MissingCount": df.isna().sum(),
    "MissingPercent": (df.isna().mean() * 100).round(2),
    "UniqueValues": df.nunique()
})

display(df_summary)

                       DataType  MissingCount  MissingPercent  UniqueValues
AnimalNumber            float64       1701003           20.02          9087
LactationNumber         float64       1701003           20.02            12
DaysInMilk              float64       1701007           20.02           870
ReproductionStatus          str       1701003           20.02             4
Avgmilkflow             float64           172            0.00           219
Flow30_60Session        float64             0            0.00           102
YieldFirst2Min_Session  float64             0            0.00          1675
YieldSession            float64             0            0.00          1010
DurationSession_sec       int64             0            0.00           604
milking                   int64             0            0.00             3

In [4]:
#apply PascalCase naming convention to the column names
df = df.rename(columns={
    "Avgmilkflow": "AverageMilkFlowKgPerMin",
    "Flow30_60Session": "MilkFlow30To60SecondsKgPerMin",
    "YieldFirst2Minute_Session": "MilkYieldFirst2MinutesKg",
    "YieldSession": "TotalMilkYieldSessionKg",
    "DurationSession_sec": "MilkingDurationSessionSeconds",
    "milking": "MilkingSession"
})

display(df.head())

,AnimalNumber,LactationNumber,DaysInMilk,ReproductionStatus,AverageMilkFlowKgPerMin,MilkFlow30To60SecondsKgPerMin,YieldFirst2Min_Session,TotalMilkYieldSessionKg,MilkingDurationSessionSeconds,MilkingSession
0,31317.0,2.0,255.0,Pregnant,2.812273,2.898455,5.874021,8.028585,168,2
1,60614.0,1.0,251.0,Pregnant,2.902991,3.801104,6.372973,7.030682,143,1
2,36947.0,1.0,183.0,Pregnant,3.401943,3.701314,7.048825,16.374685,285,3
3,31720.0,2.0,82.0,Bred,4.309128,4.799007,8.876803,18.461209,256,1
4,23630.0,6.0,182.0,Pregnant,3.719457,3.701314,7.874364,13.199538,210,3